# Generated by Django 4.0.3 on 2022-06-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aktyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=50)),
                ('mamlakat', models.CharField(max_length=50)),
                ('jins', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Kino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('yil', models.DateField()),
                ('janr', models.CharField(max_length=50)),
                ('aktyor', models.ManyToManyField(to='app1.aktyor')),
            ],
        ),
    ]
